### ISSUE TITLE
Cython compilation issues 

### ISSUE THREAD

**Issue by escorciav** [lichengunc/refer#24]
Any clue? :bulb: 
```
$ pip install -e git+https://github.com/lichengunc/refer.git#egg=refer
Obtaining refer from git+https://github.com/lichengunc/refer.git#egg=refer
  Updating ./src/refer clone
  Running command git fetch -q --tags
  Running command git reset --hard -q e3bbaa30d2ca41cf0e5c0d3819d7e4ed9fd38fff
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      /perseverant_donkey/install/bin/miniconda3/envs/awesome-condaenv-i/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /perseverant_donkey/projects/genai-research/src/refer/external/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef np.ndarray[np.double_t, ndim=1] np_poly
          n = len(poly)
          Rs = RLEs(n)
          for i, p in enumerate(poly):
              np_poly = np.array(p, dtype=np.double, order='F')
              rleFrPoly( <RLE*>&Rs._R[i], <const double*> np_poly.data, len(np_poly)/2, h, w )
                                                                                    ^
      ------------------------------------------------------------

      external/_mask.pyx:258:78: Cannot assign type 'double' to 'siz' (alias of 'unsigned long')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/perseverant_donkey/projects/genai-research/src/refer/setup.py", line 24, in <module>
          ext_modules=cythonize(ext_modules)
                      ^^^^^^^^^^^^^^^^^^^^^^
        File "/perseverant_donkey/install/bin/miniconda3/envs/awesome-condaenv-i/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/perseverant_donkey/install/bin/miniconda3/envs/awesome-condaenv-i/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: external/_mask.pyx
      Compiling external/_mask.pyx because it changed.
      [1/1] Cythonizing external/_mask.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by choasup** [comment]
ext_modules=cythonize(ext_modules, compiler_directives={'language_level': "2"}
