### ISSUE TITLE
Cython fail to compile

### ISSUE THREAD

**Issue by jsuit** [lichengunc/refer#8]
Error: 
`Error compiling Cython file: ------------------------------------------------------------ ...     cdef np.ndarray[np.double_t, ndim=1] np_poly     n = len(poly)     Rs = RLEs(n)     for i, p in enumerate(poly):         np_poly = np.array(p, dtype=np.double, order='F')         rleFrPoly( <RLE*>&Rs._R[i], <const double*> np_poly.data, len(np_poly)/2, h, w )                                                                              ^ ------------------------------------------------------------  external/_mask.pyx:258:78: Cannot assign type 'double' to 'siz' Traceback (most recent call last):   File "setup.py", line 24, in <module>     ext_modules=cythonize(ext_modules)   File "/opt/miniconda3/envs/pytorch1.6/lib/python3.6/site-packages/Cython-3.0a6-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1110, in cythonize     cythonize_one(*args)   File "/opt/miniconda3/envs/pytorch1.6/lib/python3.6/site-packages/Cython-3.0a6-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1277, in cythonize_one     raise CompileError(None, pyx_file) Cython.Compiler.Errors.CompileError: external/_mask.pyx`

python version =3.6, cython = 3.0a6

**Comment by DwanZhang-AI** [comment]
Same

**Comment by sarvghotra** [comment]
The solution given [here](https://stackoverflow.com/questions/64932145/cython-compile-error-cannot-assign-type-double-to-int-using-mingw64-in-win) worked for me.

**Comment by lucasea777** [comment]
Based on the link @sarvghotra shared:
In setup.py, replace
```
ext_modules=cythonize(ext_modules)
```
with
```
ext_modules=cythonize(ext_modules, language_level = "2")
```

**Comment by serser** [comment]
Facing `make` compile errors, any help?

```
# install pycocotools/mask locally
# copy from https://github.com/pdollar/coco.git
python setup.py build_ext --inplace
Compiling external/_mask.pyx because it changed.
[1/1] Cythonizing external/_mask.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef siz n = len(rleObjs)
    Rs = RLEs(n)
    cdef bytes py_string
    cdef char* c_string
    for i, obj in enumerate(rleObjs):
        py_string = str(obj['counts'])
                       ^
------------------------------------------------------------
external/_mask.pyx:122:23: Cannot convert Unicode string to 'bytes' implicitly, encoding required.
Traceback (most recent call last):
  File "/mnt/vlm/common/datasets/RefCOCO/refer-master/setup.py", line 24, in <module>
    ext_modules=cythonize(ext_modules, language_level = "2")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/vlm/common/env/florence-vl/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1153, in cythonize
    cythonize_one(*args)
  File "/mnt/vlm/common/env/florence-vl/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1297, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: external/_mask.pyx
make: *** [Makefile:4: all] Error 1
```

**Comment by serser** [comment]
> Facing `make` compile errors, any help?
> 
> ```
> # install pycocotools/mask locally
> # copy from https://github.com/pdollar/coco.git
> python setup.py build_ext --inplace
> Compiling external/_mask.pyx because it changed.
> [1/1] Cythonizing external/_mask.pyx
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
>     cdef siz n = len(rleObjs)
>     Rs = RLEs(n)
>     cdef bytes py_string
>     cdef char* c_string
>     for i, obj in enumerate(rleObjs):
>         py_string = str(obj['counts'])
>                        ^
> ------------------------------------------------------------
> external/_mask.pyx:122:23: Cannot convert Unicode string to 'bytes' implicitly, encoding required.
> Traceback (most recent call last):
>   File "/mnt/vlm/common/datasets/RefCOCO/refer-master/setup.py", line 24, in <module>
>     ext_modules=cythonize(ext_modules, language_level = "2")
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/vlm/common/env/florence-vl/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1153, in cythonize
>     cythonize_one(*args)
>   File "/mnt/vlm/common/env/florence-vl/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1297, in cythonize_one
>     raise CompileError(None, pyx_file)
> Cython.Compiler.Errors.CompileError: external/_mask.pyx
> make: *** [Makefile:4: all] Error 1
> ```

I am using Python3, so I have to change it to,

```
py_string = obj['counts'].encode('utf-8')
```

in `external/_mask.pyx` and it compiles with warnings only.
